import type { Metadata } from "next";
import "./globals.css";
import AnimatedLayout from "@/components/AnimatedLayout";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="dark">
        <AnimatedLayout bgImage="/images/bg.png">
          {children}
          <Toaster richColors />
        </AnimatedLayout>
      </body>
    </html>
  );
}
